
-- carga de tablas del sistema --

INSERT INTO acceso_personas_discapacidad								(`codigo`, `descripcion`) VALUES 	('1','Si');
INSERT INTO acceso_personas_discapacidad								(`codigo`, `descripcion`) VALUES 	('2','No');
INSERT INTO acreditador																	(`codigo`, `descripcion`) VALUES 	('1','CONEAU');
INSERT INTO acreditador																	(`codigo`, `descripcion`) VALUES 	('2','internacional');
INSERT INTO aprobacion																	(`codigo`, `descripcion`) VALUES 	('1','aprobado');
INSERT INTO aprobacion																	(`codigo`, `descripcion`) VALUES 	('2','desaprobado');
INSERT INTO aprobacion																	(`codigo`, `descripcion`) VALUES 	('3','retirado');
INSERT INTO area_conocimiento														(`codigo`, `descripcion`) VALUES 	('1','comunicacion');
INSERT INTO area_conocimiento														(`codigo`, `descripcion`) VALUES 	('2','matematica');
INSERT INTO area_conocimiento														(`codigo`, `descripcion`) VALUES 	('3','ciudadania');
INSERT INTO area_conocimiento														(`codigo`, `descripcion`) VALUES 	('4','ciencia');
INSERT INTO area_conocimiento														(`codigo`, `descripcion`) VALUES 	('5','tecnologia y ambiente');
INSERT INTO area_geografica															(`codigo`, `descripcion`) VALUES 	('1','urbano');
INSERT INTO area_geografica															(`codigo`, `descripcion`) VALUES 	('2','rural');
INSERT INTO areas_desempenio														(`codigo`, `descripcion`) VALUES 	('1','gestion pedagogica');
INSERT INTO areas_desempenio														(`codigo`, `descripcion`) VALUES 	('2','gestion institucional');
INSERT INTO areas_desempenio														(`codigo`, `descripcion`) VALUES 	('3','formacion docente');
INSERT INTO areas_desempenio														(`codigo`, `descripcion`) VALUES 	('4','innovacion e investigacion');
INSERT INTO caracteristicas_ie													(`codigo`, `descripcion`) VALUES 	('1','unidocente');
INSERT INTO caracteristicas_ie													(`codigo`, `descripcion`) VALUES 	('2','multigrado');
INSERT INTO caracteristicas_ie													(`codigo`, `descripcion`) VALUES 	('3','polidocente completo');
INSERT INTO ciclo																				(`codigo`, `descripcion`) VALUES 	('1','inicial');
INSERT INTO ciclo																				(`codigo`, `descripcion`) VALUES 	('2','intermedio');
INSERT INTO ciclo																				(`codigo`, `descripcion`) VALUES 	('3','superior');
INSERT INTO dimension_proyecto													(`codigo`, `descripcion`) VALUES 	('1','local');
INSERT INTO dimension_proyecto													(`codigo`, `descripcion`) VALUES 	('2','regional');
INSERT INTO dimension_proyecto													(`codigo`, `descripcion`) VALUES 	('3','nacional');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('1','1');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('2','2');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('3','3');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('4','4');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('5','5');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('6','6');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('7','7');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('8','8');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('9','9');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('10','10');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('11','11');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('12','12');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('13','13');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('14','14');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('15','15');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('16','16');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('17','17');
INSERT INTO escala_magisterial													(`codigo`, `descripcion`) VALUES 	('18','18');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('1','discapacidad intelectual');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('2','audicion y lenguaje');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('3','terapia fisica');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('4','terapia de lenguaje');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('5','terapia ocupacional');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('6','psicologa');
INSERT INTO especialidad_intervencion_temprana					(`codigo`, `descripcion`) VALUES 	('7','trabajadora social');
INSERT INTO especialidad_profesional_no_docente					(`codigo`, `descripcion`) VALUES 	('1','terapia fisica');
INSERT INTO especialidad_profesional_no_docente					(`codigo`, `descripcion`) VALUES 	('2','terapia ocupacional');
INSERT INTO especialidad_profesional_no_docente					(`codigo`, `descripcion`) VALUES 	('3','psicologo educacional');
INSERT INTO especialidad_profesional_no_docente					(`codigo`, `descripcion`) VALUES 	('4','trabajador social');
INSERT INTO estado_acreditacion													(`codigo`, `descripcion`) VALUES 	('1','acreditada');
INSERT INTO estado_acreditacion													(`codigo`, `descripcion`) VALUES 	('2','en proceso');
INSERT INTO estado_proyecto															(`codigo`, `descripcion`) VALUES 	('1','presentado');
INSERT INTO estado_proyecto															(`codigo`, `descripcion`) VALUES 	('2','cuenta con financiamiento');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('1','cuna');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('2','cuna-jardin');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('3','SET');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('4','PIET');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('5','PIETBAF');
INSERT INTO estrategias_caracteristicas									(`codigo`, `descripcion`) VALUES 	('6','PRONOEI');
INSERT INTO etapa_evaluacion_ingreso_carrera_publica		(`codigo`, `descripcion`) VALUES 	('1','primera');
INSERT INTO etapa_evaluacion_ingreso_carrera_publica		(`codigo`, `descripcion`) VALUES 	('2','segunda');
INSERT INTO etapas_curriculo														(`codigo`, `descripcion`) VALUES 	('1','formulacion');
INSERT INTO etapas_curriculo														(`codigo`, `descripcion`) VALUES 	('2','evaluacion');
INSERT INTO evento_capacitacion													(`codigo`, `descripcion`) VALUES 	('1','talleres');
INSERT INTO evento_capacitacion													(`codigo`, `descripcion`) VALUES 	('2','cursos');
INSERT INTO fase_plan																		(`codigo`, `descripcion`) VALUES 	('1','diseño');
INSERT INTO fase_plan																		(`codigo`, `descripcion`) VALUES 	('2','implementacion');
INSERT INTO fase_plan																		(`codigo`, `descripcion`) VALUES 	('3','ejecucion');
INSERT INTO fase_plan																		(`codigo`, `descripcion`) VALUES 	('4','evaluacion');
INSERT INTO fondo_regional															(`codigo`, `descripcion`) VALUES 	('1','investigacion');
INSERT INTO fondo_regional															(`codigo`, `descripcion`) VALUES 	('2','infraestructura');
INSERT INTO fondo_regional															(`codigo`, `descripcion`) VALUES 	('3','capacitacion docentes');
INSERT INTO fuente_financiamiento												(`codigo`, `descripcion`) VALUES 	('1','FONDEP');
INSERT INTO fuente_financiamiento												(`codigo`, `descripcion`) VALUES 	('2','Ipeba');
INSERT INTO grupo_etario																(`codigo`, `descripcion`) VALUES 	('1','0-2,3-5,6-11,12-16');
INSERT INTO grupo_etario																(`codigo`, `descripcion`) VALUES 	('2','12-13,12-14,15-19,25-34');
INSERT INTO grupo_etario																(`codigo`, `descripcion`) VALUES 	('3','17-18,17-19,20-24,25-34');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('1','quechua collao');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('2','quechua chanka');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('3','aymara');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('4','ashaninka');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('5','awajun');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('6','shawi');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('7','shipibo');
INSERT INTO grupo_etnico																(`codigo`, `descripcion`) VALUES 	('8','otros');
INSERT INTO instancia_gestion_educativa_descentralizada	(`codigo`, `descripcion`) VALUES 	('1','Ugel');
INSERT INTO instancia_gestion_educativa_descentralizada	(`codigo`, `descripcion`) VALUES 	('2','DRE');
INSERT INTO instancia_gestion_educativa_descentralizada	(`codigo`, `descripcion`) VALUES 	('3','Minedu');
INSERT INTO lengua_materna															(`codigo`, `descripcion`) VALUES 	('1','castellano');
INSERT INTO lengua_materna															(`codigo`, `descripcion`) VALUES 	('2','originaria');
INSERT INTO modalidad_atencion													(`codigo`, `descripcion`) VALUES 	('1','educacion a distancia');
INSERT INTO modalidad_atencion													(`codigo`, `descripcion`) VALUES 	('2','educacion en alternancia');
INSERT INTO modalidad_atencion													(`codigo`, `descripcion`) VALUES 	('3','otros');
INSERT INTO modalidad_educacion													(`codigo`, `descripcion`) VALUES 	('1','presencial');
INSERT INTO modalidad_educacion													(`codigo`, `descripcion`) VALUES 	('2','a distancia');
INSERT INTO modalidad_educativa													(`codigo`, `descripcion`) VALUES 	('1','EBR');
INSERT INTO modalidad_educativa													(`codigo`, `descripcion`) VALUES 	('2','EBA');
INSERT INTO modalidad_educativa													(`codigo`, `descripcion`) VALUES 	('3','EBE');
INSERT INTO modalidad_educativa													(`codigo`, `descripcion`) VALUES 	('4','CETPRO');
INSERT INTO nivel_gobierno															(`codigo`, `descripcion`) VALUES 	('1','nacional');
INSERT INTO nivel_gobierno															(`codigo`, `descripcion`) VALUES 	('2','regional');
INSERT INTO nivel_gobierno															(`codigo`, `descripcion`) VALUES 	('3','local');
INSERT INTO estado_logro																(`codigo`, `descripcion`) VALUES 	('1','debajo del nivel 1');
INSERT INTO estado_logro																(`codigo`, `descripcion`) VALUES 	('2','nivel 1');
INSERT INTO estado_logro																(`codigo`, `descripcion`) VALUES 	('3','nivel 2');
INSERT INTO nivel_logro																	(`codigo`, `descripcion`) VALUES 	('1','logrado');
INSERT INTO nivel_logro																	(`codigo`, `descripcion`) VALUES 	('2','no logrado');
INSERT INTO nivel_educativo															(`codigo`, `descripcion`) VALUES 	('1','inicial');
INSERT INTO nivel_educativo															(`codigo`, `descripcion`) VALUES 	('2','primaria');
INSERT INTO nivel_educativo															(`codigo`, `descripcion`) VALUES 	('3','secundaria');
INSERT INTO periodo_reporte															(`codigo`, `descripcion`) VALUES 	('1','julio');
INSERT INTO periodo_reporte															(`codigo`, `descripcion`) VALUES 	('2','diciembre');
INSERT INTO servicios_basicos														(`codigo`, `descripcion`) VALUES 	('1','agua');
INSERT INTO servicios_basicos														(`codigo`, `descripcion`) VALUES 	('2','desagüe');
INSERT INTO servicios_basicos														(`codigo`, `descripcion`) VALUES 	('3','energia electrica');
INSERT INTO sexo																				(`codigo`, `descripcion`) VALUES 	('1','Masculino');
INSERT INTO sexo																				(`codigo`, `descripcion`) VALUES 	('2','Femenino');
INSERT INTO tematica																		(`codigo`, `descripcion`) VALUES 	('1','investigacion');
INSERT INTO tematica																		(`codigo`, `descripcion`) VALUES 	('2','innovacion');
INSERT INTO tematica_franja_horaria											(`codigo`, `descripcion`) VALUES 	('1','educacion');
INSERT INTO tematica_franja_horaria											(`codigo`, `descripcion`) VALUES 	('2','cultura');
INSERT INTO tematica_franja_horaria											(`codigo`, `descripcion`) VALUES 	('3','formacion ciudadana');
INSERT INTO tematicas_especializacion										(`codigo`, `descripcion`) VALUES 	('1','comunicacion');
INSERT INTO tematicas_especializacion										(`codigo`, `descripcion`) VALUES 	('2','matematicas');
INSERT INTO tematicas_especializacion										(`codigo`, `descripcion`) VALUES 	('3','ciudadania');
INSERT INTO tematicas_especializacion										(`codigo`, `descripcion`) VALUES 	('4','ciencia');
INSERT INTO t_ie																				(`codigo`, `descripcion`) VALUES 	('1','unidocente');
INSERT INTO t_ie																				(`codigo`, `descripcion`) VALUES 	('2','multigrado');
INSERT INTO t_ie																				(`codigo`, `descripcion`) VALUES 	('3','completa');
INSERT INTO t_ie_superior																(`codigo`, `descripcion`) VALUES 	('1','universitaria');
INSERT INTO t_ie_superior																(`codigo`, `descripcion`) VALUES 	('2','tecnica');
INSERT INTO t_programa_desarrollo_profesional						(`codigo`, `descripcion`) VALUES 	('1','primero');
INSERT INTO t_programa_desarrollo_profesional						(`codigo`, `descripcion`) VALUES 	('2','segundo');
INSERT INTO t_actividades_educativas										(`codigo`, `descripcion`) VALUES 	('1','campanias de promocion');
INSERT INTO t_actividades_educativas										(`codigo`, `descripcion`) VALUES 	('2','prevencion');
INSERT INTO t_actividades_educativas										(`codigo`, `descripcion`) VALUES 	('3','otros');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('1','zona rural');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('2','zona de frontera');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('3','VRAEM');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('4','escuelas unidocentes');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('5','escuelas multigrado');
INSERT INTO t_asignaciones_especiales										(`codigo`, `descripcion`) VALUES 	('6','escuelas bilingües');
INSERT INTO t_centros_acopio														(`codigo`, `descripcion`) VALUES 	('1','bibliotecas');
INSERT INTO t_centros_acopio														(`codigo`, `descripcion`) VALUES 	('2','ludotecas');
INSERT INTO t_centros_acopio														(`codigo`, `descripcion`) VALUES 	('3','videotecas');
INSERT INTO t_centros_acopio														(`codigo`, `descripcion`) VALUES 	('4','otros');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('1','linea telefonica');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('2','cable');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('3','satelite');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('4','red inalambrica');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('5','LMDS');
INSERT INTO t_conexion_internet													(`codigo`, `descripcion`) VALUES 	('6','PLC');
INSERT INTO t_becas_por_formacion			  								(`codigo`, `descripcion`) VALUES 	('1','inicial');
INSERT INTO t_becas_por_formacion		  									(`codigo`, `descripcion`) VALUES 	('2','en servicio');
INSERT INTO t_becas_por_ubicacion               				(`codigo`, `descripcion`) VALUES 	('1','nacionales');
INSERT INTO t_becas_por_ubicacion  											(`codigo`, `descripcion`) VALUES 	('2','internacionales');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('1','intelectual');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('2','audicion y lenguaje');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('3','visual');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('4','sordo ceguera');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('5','motora');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('6','terapia fisica');
INSERT INTO t_discapacidad															(`codigo`, `descripcion`) VALUES 	('7','terapia ocupacional');
INSERT INTO t_egresado																	(`codigo`, `descripcion`) VALUES 	('1','programa');
INSERT INTO t_egresado																	(`codigo`, `descripcion`) VALUES 	('2','acreditacion');
INSERT INTO t_empresas																	(`codigo`, `descripcion`) VALUES 	('1','micro');
INSERT INTO t_empresas																	(`codigo`, `descripcion`) VALUES 	('2','pequenia');
INSERT INTO t_empresas																	(`codigo`, `descripcion`) VALUES 	('3','mediana');
INSERT INTO t_empresas																	(`codigo`, `descripcion`) VALUES 	('4','grande');
INSERT INTO t_especializacion_docentes									(`codigo`, `descripcion`) VALUES 	('1','discapacidad intelectual');
INSERT INTO t_especializacion_docentes									(`codigo`, `descripcion`) VALUES 	('2','audicion y lenguaje');
INSERT INTO t_especializacion_docentes									(`codigo`, `descripcion`) VALUES 	('3','discapacidad visual');
INSERT INTO t_especializacion_docentes									(`codigo`, `descripcion`) VALUES 	('4','sordo ceguera');
INSERT INTO t_evaluacion_desempenio_extraordinaria			(`codigo`, `descripcion`) VALUES 	('1','primera');
INSERT INTO t_evaluacion_desempenio_extraordinaria			(`codigo`, `descripcion`) VALUES 	('2','segunda');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('1','FIDECOM');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('2','FONDECYT');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('3','FINCYT');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('4','FCNR');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('5','FONDAM');
INSERT INTO t_fondos_concursables												(`codigo`, `descripcion`) VALUES 	('6','Otros');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('1','actualizacion');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('2','especializacion');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('3','diplomados');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('4','segunda especialidad');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('5','acompañamiento pedagogico');
INSERT INTO t_formacion_en_servicio_minedu							(`codigo`, `descripcion`) VALUES 	('6','cursos cortos');
INSERT INTO t_gestion_ie																(`codigo`, `descripcion`) VALUES 	('1','publico');
INSERT INTO t_gestion_ie																(`codigo`, `descripcion`) VALUES 	('2','privado');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('1','trabajo en zonas rurales');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('2','en zonas de frontera');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('3','en VRAEM');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('4','enseñanza en escuela unidocentes');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('5','multigrado');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('6','bilingües');
INSERT INTO t_incentivos_docentes												(`codigo`, `descripcion`) VALUES 	('7','acceso a cargos');
INSERT INTO t_instituciones_financiadoras								(`codigo`, `descripcion`) VALUES 	('1','FONDEP');
INSERT INTO t_instituciones_financiadoras								(`codigo`, `descripcion`) VALUES 	('2','Gobierno regional');
INSERT INTO t_instituciones_financiadoras								(`codigo`, `descripcion`) VALUES 	('3','gobierno local');
INSERT INTO t_instituciones_financiadoras								(`codigo`, `descripcion`) VALUES 	('4','otros');
INSERT INTO t_institucion																(`codigo`, `descripcion`) VALUES 	('1','publica');
INSERT INTO t_institucion																(`codigo`, `descripcion`) VALUES 	('2','privada');
INSERT INTO t_institucion																(`codigo`, `descripcion`) VALUES 	('3','gestion mixta');
INSERT INTO t_institucion_educativa											(`codigo`, `descripcion`) VALUES 	('1','universidad');
INSERT INTO t_institucion_educativa											(`codigo`, `descripcion`) VALUES 	('2','instituto');
INSERT INTO t_institucion_armada												(`codigo`, `descripcion`) VALUES 	('1','ejercito');
INSERT INTO t_institucion_armada												(`codigo`, `descripcion`) VALUES 	('2','marina');
INSERT INTO t_institucion_armada												(`codigo`, `descripcion`) VALUES 	('3','fuerza aerea');
INSERT INTO t_institucion_armada												(`codigo`, `descripcion`) VALUES 	('4','policia');
INSERT INTO t_institucion_que_brinda_capacitacion				(`codigo`, `descripcion`) VALUES 	('1','Minedu');
INSERT INTO t_institucion_que_brinda_capacitacion				(`codigo`, `descripcion`) VALUES 	('2','Midis');
INSERT INTO t_institucion_que_brinda_capacitacion				(`codigo`, `descripcion`) VALUES 	('3','Mimp');
INSERT INTO t_lenguaje																	(`codigo`, `descripcion`) VALUES 	('1','L1');
INSERT INTO t_lenguaje																	(`codigo`, `descripcion`) VALUES 	('2','L2');
INSERT INTO t_material_distribuido											(`codigo`, `descripcion`) VALUES 	('1','comunicacion');
INSERT INTO t_material_distribuido											(`codigo`, `descripcion`) VALUES 	('2','matematica');
INSERT INTO t_material_distribuido											(`codigo`, `descripcion`) VALUES 	('3','ciudadania');
INSERT INTO t_material_distribuido											(`codigo`, `descripcion`) VALUES 	('4','ciencia');
INSERT INTO t_material_distribuido											(`codigo`, `descripcion`) VALUES 	('5','tecnologia y ambiente');
INSERT INTO t_medio_comunicacion												(`codigo`, `descripcion`) VALUES 	('1','radio');
INSERT INTO t_medio_comunicacion												(`codigo`, `descripcion`) VALUES 	('2','television');
INSERT INTO t_municipalidades														(`codigo`, `descripcion`) VALUES 	('1','A');
INSERT INTO t_municipalidades														(`codigo`, `descripcion`) VALUES 	('2','B');
INSERT INTO t_municipalidades														(`codigo`, `descripcion`) VALUES 	('3','menos de 500 viviendas');
INSERT INTO t_municipalidades														(`codigo`, `descripcion`) VALUES 	('4','mas de 500 viviendas');
INSERT INTO t_pasantias																	(`codigo`, `descripcion`) VALUES 	('1','nacionales');
INSERT INTO t_pasantias																	(`codigo`, `descripcion`) VALUES 	('2','internacionales');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('1','zona rural');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('2','zona de frontera');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('3','VRAEM');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('4','escuelas unidocentes');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('5','escuelas multigrado');
INSERT INTO t_plazas																		(`codigo`, `descripcion`) VALUES 	('6','escuelas bilingües');
INSERT INTO t_programa																	(`codigo`, `descripcion`) VALUES 	('1','proteccion');
INSERT INTO t_programa																	(`codigo`, `descripcion`) VALUES 	('2','prevencion al maltrato infantil');
INSERT INTO t_programa																	(`codigo`, `descripcion`) VALUES 	('3','violencia familiar');
INSERT INTO t_programa_social_menores_3_anios						(`codigo`, `descripcion`) VALUES 	('1','salud');
INSERT INTO t_programa_social_menores_3_anios						(`codigo`, `descripcion`) VALUES 	('2','educacion');
INSERT INTO t_programa_social_menores_3_anios						(`codigo`, `descripcion`) VALUES 	('3','MIDIS');
INSERT INTO t_programa_social_menores_3_anios						(`codigo`, `descripcion`) VALUES 	('4','MIMP');
INSERT INTO t_programa_universitario										(`codigo`, `descripcion`) VALUES 	('1','Bachillerato');
INSERT INTO t_programa_universitario										(`codigo`, `descripcion`) VALUES 	('2','Licenciatura');
INSERT INTO t_programas_apoyo_familia										(`codigo`, `descripcion`) VALUES 	('1','entidad publica');
INSERT INTO t_programas_apoyo_familia										(`codigo`, `descripcion`) VALUES 	('2','gobierno local/regional');
INSERT INTO t_programas_apoyo_familia										(`codigo`, `descripcion`) VALUES 	('3','otros');
INSERT INTO t_proyecto_educativo_financiado							(`codigo`, `descripcion`) VALUES 	('1','innovacion');
INSERT INTO t_proyecto_educativo_financiado							(`codigo`, `descripcion`) VALUES 	('2','productivo');
INSERT INTO t_proyecto_educativo_financiado							(`codigo`, `descripcion`) VALUES 	('3','otros');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('1','atencion a la diversidad');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('2','metodologias participativas');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('3','evaluacion');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('4','clima de aula');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('5','valores eticos');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('6','uso de TIC');
INSERT INTO t_proyectos_presentados											(`codigo`, `descripcion`) VALUES 	('7','otros');
INSERT INTO t_recurso_brindado													(`codigo`, `descripcion`) VALUES 	('1','bibliotecas');
INSERT INTO t_recurso_brindado													(`codigo`, `descripcion`) VALUES 	('2','materiales a docentes');
INSERT INTO t_recurso_brindado													(`codigo`, `descripcion`) VALUES 	('3','laboratorios');
INSERT INTO t_recurso_brindado													(`codigo`, `descripcion`) VALUES 	('4','acceso a internet');
INSERT INTO t_recurso_brindado													(`codigo`, `descripcion`) VALUES 	('5','material deportivo');
INSERT INTO t_reparacion																(`codigo`, `descripcion`) VALUES 	('1','total');
INSERT INTO t_reparacion																(`codigo`, `descripcion`) VALUES 	('2','parcial');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('1','zona rural');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('2','zona de frontera');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('3','VRAEM');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('4','escuelas unidocentes');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('5','escuelas multigrado');
INSERT INTO t_situaciones_especiales										(`codigo`, `descripcion`) VALUES 	('6','escuelas bilingües');